### ISSUE TITLE
Can someone share the pre-trained Super SloMo model checkpoint via another cloud drive?

### ISSUE THREAD

**Issue by fleebeatles** [SensorsINI/v2e#14]
Hi, I am from mainland China and I have tried to download the _superslomo39.ckp_ from Google drive, but it seemed that that couldn't be complished. Can someone share the file via another cloud drive, like Onedrive or something else? Thanks a lot.

**Comment by duguyue100** [comment]
Maybe try this link: https://share.weiyun.com/BEZ3R9V9

This is the easiest drive I have access to. Let me know if this works.

Yuhuang.

**Comment by fleebeatles** [comment]
> Maybe try this link: https://share.weiyun.com/BEZ3R9V9
> 
> This is the easiest drive I have access to. Let me know if this works.
> 
> Yuhuang.

It helped me with the problem. Thank you, Yuhuang!
