### ISSUE TITLE
--skip_video_output failed

### ISSUE THREAD

**Issue by GEN418** [SensorsINI/v2e#21]
When this parameter is added to the command line,  the procedure still produces video_orig.avi and video_slomo.avi.

**Comment by duguyue100** [comment]
Hi, @GEN418 , this is a good find. I include this argument but not fully tested.

Now I fixed the bug and the argument will properly suppress all video outputs.

You can now pull and try again, let me know if it's not working for you.

Yuhuang.

**Comment by GEN418** [comment]
Hi, @duguyue100. After pulling and running, I meet a mistake caused by the modification, so I try to fix it by changing 'is none' to 'is not none'  in v2ecore/slomo.py, the mistake and bug are gone. Thank you for your answer.
Gen.
![2021-06-17 22-14-06屏幕截图](https://user-images.githubusercontent.com/40853724/122416716-8ad54a00-cfbb-11eb-878a-ea9af0dbd9da.png)

**Comment by duguyue100** [comment]
Definitely, I overkilled when I made the bug fixes, now it should be ok. thanks for reporting!
