### ISSUE TITLE
Setting Initial Timestamp

### ISSUE THREAD

**Issue by kochanha** [SensorsINI/v2e#24]
Hello :)
First of all, thanks for this amazing event simulator!
I have a query about setting a initial timestamp.
Is there any way I can set up the initial timestamp from the event?
Thank you

**Comment by tobidelbruck** [comment]
Thanks!

What do you mean? You mean the timestamp of the very first event in the 
recording?

That should be couple lines of code to add either in v2e.py or emulator.py.

Tobi
