### ISSUE TITLE
DAVIS camera conversion Dataset error when run the command "python -m dataset_scripts.ddd.ddd_extract_data.py -h"

### ISSUE THREAD

**Issue by angelsb008** [SensorsINI/v2e#26]
I've tried run all the commands in this section, but the console give me the present error: 

(v2e) PS C:\Users\laloh\v2e> cd input
(v2e) PS C:\Users\laloh\v2e\input> mkdir -p input

    Directorio: C:\Users\laloh\v2e\input

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----     30/11/2021  12:39 p. m.                input

(v2e) PS C:\Users\laloh\v2e\input> mv rec1501902136.hdf5 ./input
(v2e) PS C:\Users\laloh\v2e\input> python -m dataset_scripts.ddd.ddd_extract_data.py -h
Traceback (most recent call last):
  File "C:\Users\laloh\anaconda3\envs\v2e\lib\runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\laloh\anaconda3\envs\v2e\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "c:\users\laloh\v2e\dataset_scripts\ddd\ddd_extract_data.py", line 16, in <module>
    from v2e.ddd20_utils import ddd_h5_reader
ModuleNotFoundError: No module named 'v2e.ddd20_utils'; 'v2e' is not a package
(v2e) PS C:\Users\laloh\v2e\input>

**Comment by tobidelbruck** [comment]
yes, sorry about that. The DDD20 specialized scripts have not been 
tested for some time and might not be working with the latest v2e 
modules. We can try to take a look at this exception. Thanks for 
pointing out the script "chdir input; mkdir -p input"; it doesn't really 
make sense.  The base examples at start of README should definitely be 
working correctly assuming you have a suitable conda env set up.
