### ISSUE TITLE
128x128 output not supported

### ISSUE THREAD

**Issue by mahmoudakl** [SensorsINI/v2e#27]
Hello,

I'm trying to generate events from a sequence of images. When I tried to use the --dvs128 option that is specified in the readme I got the following error message:

> ValueError: AEDAT-2.0 output width=128 height=128 not supported; add your camera to v2ecore.output.aedat2_output or use one of the predefined DVS cameras, e.g. --dvs346 or --dvs240

Using --dvs240 and --dvs346 works, I'm wondering, is the --dvs128 option not supported?

Thanks!

**Comment by tobidelbruck** [comment]
Hmm, we maybe didn't implement it. It should be very easy to add 
following AEDAT-2.0 data structure instructions from

https://inivation.github.io/inivation-docs/Software%20user%20guides/AEDAT_file_formats.html#aedat-20

The DVS128 2.0 format is the same as 1.0 format but address is widened 
to 32 bits (unused bits are set to zero). It is much simpler than the 
DAVIS AEDAT-2.0 format. But v2e only writes DVS events, not frames or 
IMU samples so far, for DAVIS cameras.
