### ISSUE TITLE
Corresponding pixel for each event

### ISSUE THREAD

**Issue by Johnzdh** [SensorsINI/v2e#31]
How can I get the corresponding pixel in the videos for each event? Is there any way to get it?

**Comment by tobidelbruck** [comment]
Do you mean the x,y address of the pixel in the frame of the source 
video that produced the upsampled video that resulted in that particular 
event? If so, it's just that x,y pixel. You can calculate the frame 
number from the event time and the source frame rate.

**Comment by Johnzdh** [comment]
Thanks for your reply.
