### ISSUE TITLE
How to save events data to a CSV file in the form (step : int, x, y, p )?

### ISSUE THREAD

**Issue by oshima-yoppi** [SensorsINI/v2e#34]
Hello.
I want to save events data to a CSV file in the form (time-step : int, x, y, p ), not (time, x, y, p)
How should I do?

**Comment by tobidelbruck** [comment]
I think you could easily modify 
https://github.com/SensorsINI/v2e/blob/master/v2ecore/output/ae_text_output.py

**Comment by oshima-yoppi** [comment]
Thanks for answering.
I'll try
