### ISSUE TITLE
Incorrect x,y order in ae_text_output.appendEvents()

### ISSUE THREAD

**Issue by abdulmohsij** [SensorsINI/v2e#37]
EventEmulator.generate_events() returns events as an np.ndarray with each row being: [timestamp, y cordinate, x cordinate, sign of event]

These events are then passed into the text output:
self.dvs_text.appendEvents(events)

In appendEvents:
x = events[:, 1].astype(np.int32)
...
y = events[:, 2].astype(np.int32)

This is incorrect.
It should be:
x = events[:, 2].astype(np.int32)
...
y = events[:, 1].astype(np.int32)

**Comment by tobidelbruck** [comment]
Thanks, I agree. This could mess up some users who have adapted to this order.  I have pushed this change to master and will make additional pushes to document if needed.

**Comment by tobidelbruck** [comment]
This push was wrong, it was based on incorrect docstring. See #48 for continued thread. Order in text output is again correct.
