### ISSUE TITLE
moving_dot with --synthetic_input argument did not generated any video 

### ISSUE THREAD

**Issue by gwgknudayanga** [SensorsINI/v2e#44]
Hi, 
I have executed the following command to generate synthesized video for moving dot. But in the result folder, it has video files which are zero in size. Is there anything that i need to modify?
v2e --leak_rate=0 --shot=0 --cutoff_hz=300 --sigma_thr=.08 --pos_thr=.15 --neg_thr=.15 --dvs_exposure duration .01 --output_folder particles-slightly-less-faint-fast-2-particles --unique_output --dvs_aedat2=particles --output_width=346 --output_height=260 --batch=64 --disable_slomo --synthetic_input=scripts.moving_dot --t_total=3 --contrast=1.15 --radius=.3 --dt=0.001 --num_particles=2  --ignore-gooey

Actually the process always stop after 5% of the frame generation completes.
INFO:v2ecore.v2e_args:DVS frame expsosure mode ExposureMode.DURATION: frame rate 100.0
INFO:v2ecore.emulator:ON/OFF log_e temporal contrast thresholds: 0.15 / 0.15 +/- 0.08
INFO:v2ecore.emulator:opening AEDAT-2.0 output file D:\DTU\ResearchWork\v2e\particles-slightly-less-faint-fast-2-particles-5\particles.aedat
INFO:root:opening AEDAT-2.0 output file D:\DTU\ResearchWork\v2e\particles-slightly-less-faint-fast-2-particles-5\particles.aedat in binary mode
INFO:v2ecore.output.aedat2_output:opened D:\DTU\ResearchWork\v2e\particles-slightly-less-faint-fast-2-particles-5\particles.aedat for DVS output data for jAER
dvs:   5%|███▉                                                                     | 162/3000 [00:01<00:12, 228.19fr/s]

Thank you.

Thanks and Rgds,
Udayanga

**Comment by tobidelbruck** [comment]
I haven't checked that script for some time but please post here (maybe 
as file attachment) the whole output. If I can find the time I will try 
to run it too on my home PC that is all setup for v2e.

What release/branch/commit are you running exactly?

Tobi

**Comment by gwgknudayanga** [comment]
i checked out it on last Monday (12th September) actually.

**Comment by tobidelbruck** [comment]
Ok, I will see if I can tell what is wrong with moving_dot in current 
master ASAP. In the meantime you are welcome to post logging output from 
your run.

**Comment by tobidelbruck** [comment]
I have used synthetic input recently without problems, so closing this issue
