### ISSUE TITLE
Setting arbitrary output size for v2e output dimension

### ISSUE THREAD

**Issue by gwgknudayanga** [SensorsINI/v2e#45]
Hi,
Is it possible to set the output size of the v2e as 100x100 instead of the dimension of --dvs346?
actually I set ---outptut_width and --output_height to 100 , but it gave error saying to set dvs240 or dvs 346.
Actually i need to generate events for events of size 100x100 dimension. 
Thanks !

**Comment by tobidelbruck** [comment]
Absolutely, you can use --output_width and --output_height. However note 
that you also need to adapt the aedaat output class to write an 
AEDAT-2.0 format, or else just use a subspace of the DVS128 class.

Tobi

**Comment by gwgknudayanga** [comment]
Thanks Tobi,
I have added it like this to the file.
SUPPORTED_SIZES=((346,260),(240,180),(100,100))
And then run again the command. But still it did not run correctly. Do i need to build the code or something like that?
If it is how should i proceed? . Thank you !
Thanks and Rgds,
Udayanga

**Comment by tobidelbruck** [comment]
Just below SUPPORTED_SIZES in the file you can see the switch statement. 
Please try to look at code before posting.

**Comment by gwgknudayanga** [comment]
> 

Sorry for that , Thank you !

**Comment by tobidelbruck** [comment]
What output do you want? Please be more specific and provide logging output.

If you want AEDAT-2.0 format you will need to modify /add to the 
aedat_output.py. For text output you shouldn't need to change anything. 
Just disable the aedat output (please read the --help output)

**Comment by gwgknudayanga** [comment]
Thanks Tobi. I disabled the aedat output and used h5 output.

**Comment by tobidelbruck** [comment]
It is very easy to clone the DVS640 class in jAER to use jAER to play with the output of v2e. You just need to make the AER address format compatible.  It is pure DVS output so very simple to pack into 32-bit int address field supported by AEDAT-2.0
