### ISSUE TITLE
cutoff frequency and time constant warning

### ISSUE THREAD

**Issue by gwgknudayanga** [SensorsINI/v2e#46]
Hi, 

Following the v2e paper, to synthesize bright events i set the cutoff frequency value to 200 Hz. And the DVS timestamp resolution is set to 1ms.But then it gave the following warning. That means to synthesize events in bright mode (with 200Hz cutoff frequency) we always need to set the set the DVS timestamp resolution less than 1ms (in microsecond range) ? isn't it? 

[1;31mWARNING[1;0m - Lowpass 3dB cutoff is f_3dB=200Hz (time constant tau=795.77us) with sample rate fs=1kHz (sample interval dt=1ms) ,
  but this results in large IIR mixing factor eps = dt/tau = 1.257 >  0.3 (maxeps),

Thanks and Rgds,
Udayanga

**Comment by tobidelbruck** [comment]
Sorry for very late reply, just came across this github notification.
Yes, to properly filter the photoreceptor output, you must set a frame interval for upsampling via superslo mo that is sufficiently shorter than the lowpass filter time constant. I.e. if your cutoff frequency is 100Hz, then tau=1/(2*pi*100Hz)=1.6ms, so the frame interval has to be some small fraction of 1.6ms, e.g. 500us. It means a lot of computation unfortunately.

**Comment by tobidelbruck** [comment]
Yes, if you want to model the motion blurring (which is pretty minimal 
except for fast moving stuff), then you need to lowpass filter the 
photoreceptor output. You can try turning it off and carefully 
inspecting the DVS output; maybe it is not important for your 
application. I recommend a native AER viewer that allows you to set the 
integration time of the DVS frames. Or else you can try outputting DVS 
frame videos with short and longer integration times.
