### ISSUE TITLE
Problem about downloading the Super-SloMo model.

### ISSUE THREAD

**Issue by SYuan-X** [SensorsINI/v2e#62]
Hello author, this is a very meaningful work. 

I am trying to apply this code to my video but I met a small problem when runnig this code. When I try to download the Super-SloMo pre-trained model, 404 error happened. Can you provide another way to download the model? thank you so much!

The output on colab looks like this:
--2023-11-09 09:57:46--  https://docs.google.com/uc?export=download&confirm=&id=17QSN207h05S_b2ndXjLrqPbBTnYIl0Vb
Resolving docs.google.com (docs.google.com)... 108.177.98.139, 108.177.98.113, 108.177.98.100, ...
Connecting to docs.google.com (docs.google.com)|108.177.98.139|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-11-09 09:57:46 ERROR 404: Not Found.

**Comment by LI474525323** [comment]
Yes, I can't download the file either

**Comment by duguyue100** [comment]
Guys, I have the file now, will reupload and update the link soon.

**Comment by duguyue100** [comment]
@SYuan-X  @LI474525323  I've updated the link in the readme and in the colab notebook. Please check it out, I will close this issue for now.

**Comment by LI474525323** [comment]
thank you very much!



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yuhuang ***@***.***&gt;; 
发送时间: 2023年11月10日(星期五) 凌晨1:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [SensorsINI/v2e] Problem about downloading the Super-SloMo model. (Issue #62)





 
Closed #62 as completed.
